import json
import pkg_resources
import os
from dotenv import load_dotenv

from mkidcontrol.commands import COMMAND_DICT

from mkidcontrol.agents.xkid.heatswitchAgent import TS_KEYS as TS_KEYS_hs
from mkidcontrol.agents.lakeshore336Agent import TS_KEYS as TS_KEYS_ls336
from mkidcontrol.agents.lakeshore372Agent import TS_KEYS as TS_KEYS_ls372
from mkidcontrol.agents.lakeshore625Agent import TS_KEYS as TS_KEYS_ls625
from mkidcontrol.agents.xkid.focusAgent import TS_KEYS as TS_KEYS_focus
from mkidcontrol.agents.xkid.magnetAgent import TS_KEYS as TS_KEYS_magnet

# TODO: Make sure all schema keys are accounted for
REDIS_DB = 0

REDIS_TS_RETENTION = 60 * 60 * 1000  # 60 min


TS_KEYS = ('status:temps:50k-stage:temp', 'status:temps:50k-stage:voltage', 'status:temps:3k-stage:temp',
           'status:temps:3k-stage:voltage', 'status:temps:1k-stage:temp', 'status:temps:1k-stage:resistance',
           'status:temps:device-stage:temp', 'status:temps:device-stage:resistance', 'status:magnet:current',
           'status:magnet:field', 'status:device:ls625:output-voltage', 'status:device:heatswitch:motor:position',
           'status:device:focus:position:mm', 'status:device:focus:position:encoder')

REDIS_TS_KEYS = tuple(set(TS_KEYS_hs + TS_KEYS_ls336 + TS_KEYS_ls372 +
                          TS_KEYS_ls625 + TS_KEYS_magnet + TS_KEYS_focus + TS_KEYS))

REDIS_STATUS_KEYS = ('status:device:heatswitch:position',
                     'status:device:ls336:status',
                     'status:device:ls372:status',
                     'status:device:ls625:status',
                     'status:device:heatswitch:status',
                     'status:device:conex:controller-status',
                     'status:device:conex:controller-state',
                     'status:device:conex:position-x',
                     'status:device:conex:position-y',
                     'status:magnet:state',
                     'status:magnet:status',
                     "tcs:airmass",
                     "tcs:rotoff",
                     "tcs:ra",
                     "tcs:dec",
                     "tcs:el",
                     "tcs:az")

FLASK_CHART_KEYS = {'Device T': 'status:temps:device-stage:temp',
                    'Device R': 'status:temps:device-stage:resistance',
                    '1k Stage T': 'status:temps:1k-stage:temp',
                    '1k Stage R': 'status:temps:1k-stage:resistance',
                    '3k Stage T': 'status:temps:3k-stage:temp',
                    '3k Stage V': 'status:temps:3k-stage:voltage',
                    '50k Stage T': 'status:temps:50k-stage:temp',
                    '50k Stage V': 'status:temps:50k-stage:voltage',
                    'Magnet I': 'status:magnet:current',
                    'Magnet Field': 'status:magnet:field',
                    'LS625 Output V': 'status:device:ls625:output-voltage'}

FLASK_TCS_KEYS = ("tcs:airmass", "tcs:rotoff", "tcs:ra", "tcs:dec", "tcs:el", "tcs:az")

FLASK_KEYS = list(COMMAND_DICT.keys()) + list(REDIS_TS_KEYS) + list(REDIS_STATUS_KEYS)

REDIS_SCHEMA = {'timeseries': {k: REDIS_TS_RETENTION for k in REDIS_TS_KEYS},
                'channels': (),
                'keys': {'device-settings:ls336:input-channel-a:name': '',
                         'device-settings:ls336:input-channel-b:name': '',
                         'device-settings:ls336:input-channel-c:name': '3K Diode',
                         'device-settings:ls336:input-channel-d:name': '50K Diode',
                         'device-settings:ls336:input-channel-a:sensor-type': 'Disabled',
                         'device-settings:ls336:input-channel-b:sensor-type': 'Disabled',
                         'device-settings:ls336:input-channel-c:sensor-type': 'Diode',
                         'device-settings:ls336:input-channel-d:sensor-type': 'Diode',
                         'device-settings:ls336:input-channel-a:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-b:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-c:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-d:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-a:compensation': 'False',
                         'device-settings:ls336:input-channel-b:compensation': 'False',
                         'device-settings:ls336:input-channel-c:compensation': 'False',
                         'device-settings:ls336:input-channel-d:compensation': 'False',
                         'device-settings:ls336:input-channel-a:units': 'Kelvin',
                         'device-settings:ls336:input-channel-b:units': 'Kelvin',
                         'device-settings:ls336:input-channel-c:units': 'Kelvin',
                         'device-settings:ls336:input-channel-d:units': 'Kelvin',
                         'device-settings:ls336:input-channel-a:input-range': '30000.0 \u03A9',
                         'device-settings:ls336:input-channel-b:input-range': '30000.0 \u03A9',
                         'device-settings:ls336:input-channel-c:input-range': '2.5 V',
                         'device-settings:ls336:input-channel-d:input-range': '2.5 V',
                         'device-settings:ls336:input-channel-a:curve': 8,
                         'device-settings:ls336:input-channel-b:curve': 8,
                         'device-settings:ls336:input-channel-c:curve': 2,
                         'device-settings:ls336:input-channel-d:curve': 2,
                         'device-settings:ls336:curve-21:curve-name': 'RO600          ',
                         'device-settings:ls336:curve-22:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-23:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-24:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-25:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-26:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-27:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-28:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-29:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-30:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-31:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-32:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-33:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-34:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-35:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-36:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-37:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-38:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-39:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-40:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-41:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-42:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-43:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-44:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-45:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-46:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-47:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-48:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-49:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-50:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-51:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-52:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-53:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-54:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-55:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-56:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-57:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-58:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-59:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-21:serial-number': '3856      ',
                         'device-settings:ls336:curve-22:serial-number': '          ',
                         'device-settings:ls336:curve-23:serial-number': '          ',
                         'device-settings:ls336:curve-24:serial-number': '          ',
                         'device-settings:ls336:curve-25:serial-number': '          ',
                         'device-settings:ls336:curve-26:serial-number': '          ',
                         'device-settings:ls336:curve-27:serial-number': '          ',
                         'device-settings:ls336:curve-28:serial-number': '          ',
                         'device-settings:ls336:curve-29:serial-number': '          ',
                         'device-settings:ls336:curve-30:serial-number': '          ',
                         'device-settings:ls336:curve-31:serial-number': '          ',
                         'device-settings:ls336:curve-32:serial-number': '          ',
                         'device-settings:ls336:curve-33:serial-number': '          ',
                         'device-settings:ls336:curve-34:serial-number': '          ',
                         'device-settings:ls336:curve-35:serial-number': '          ',
                         'device-settings:ls336:curve-36:serial-number': '          ',
                         'device-settings:ls336:curve-37:serial-number': '          ',
                         'device-settings:ls336:curve-38:serial-number': '          ',
                         'device-settings:ls336:curve-39:serial-number': '          ',
                         'device-settings:ls336:curve-40:serial-number': '          ',
                         'device-settings:ls336:curve-41:serial-number': '          ',
                         'device-settings:ls336:curve-42:serial-number': '          ',
                         'device-settings:ls336:curve-43:serial-number': '          ',
                         'device-settings:ls336:curve-44:serial-number': '          ',
                         'device-settings:ls336:curve-45:serial-number': '          ',
                         'device-settings:ls336:curve-46:serial-number': '          ',
                         'device-settings:ls336:curve-47:serial-number': '          ',
                         'device-settings:ls336:curve-48:serial-number': '          ',
                         'device-settings:ls336:curve-49:serial-number': '          ',
                         'device-settings:ls336:curve-50:serial-number': '          ',
                         'device-settings:ls336:curve-51:serial-number': '          ',
                         'device-settings:ls336:curve-52:serial-number': '          ',
                         'device-settings:ls336:curve-53:serial-number': '          ',
                         'device-settings:ls336:curve-54:serial-number': '          ',
                         'device-settings:ls336:curve-55:serial-number': '          ',
                         'device-settings:ls336:curve-56:serial-number': '          ',
                         'device-settings:ls336:curve-57:serial-number': '          ',
                         'device-settings:ls336:curve-58:serial-number': '          ',
                         'device-settings:ls336:curve-59:serial-number': '          ',
                         'device-settings:ls336:curve-21:curve-data-format': 'OHMS_PER_KELVIN',
                         'device-settings:ls336:curve-22:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-23:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-24:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-25:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-26:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-27:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-28:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-29:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-30:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-31:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-32:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-33:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-34:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-35:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-36:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-37:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-38:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-39:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-40:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-41:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-42:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-43:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-44:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-45:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-46:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-47:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-48:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-49:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-50:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-51:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-52:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-53:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-54:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-55:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-56:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-57:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-58:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-59:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-1:temperature-limit': 0,
                         'device-settings:ls336:curve-2:temperature-limit': 0,
                         'device-settings:ls336:curve-3:temperature-limit': 0,
                         'device-settings:ls336:curve-4:temperature-limit': 0,
                         'device-settings:ls336:curve-5:temperature-limit': 0,
                         'device-settings:ls336:curve-6:temperature-limit': 0,
                         'device-settings:ls336:curve-7:temperature-limit': 0,
                         'device-settings:ls336:curve-8:temperature-limit': 0,
                         'device-settings:ls336:curve-9:temperature-limit': 0,
                         'device-settings:ls336:curve-10:temperature-limit': 0,
                         'device-settings:ls336:curve-11:temperature-limit': 0,
                         'device-settings:ls336:curve-12:temperature-limit': 0,
                         'device-settings:ls336:curve-13:temperature-limit': 0,
                         'device-settings:ls336:curve-14:temperature-limit': 0,
                         'device-settings:ls336:curve-15:temperature-limit': 0,
                         'device-settings:ls336:curve-16:temperature-limit': 0,
                         'device-settings:ls336:curve-17:temperature-limit': 0,
                         'device-settings:ls336:curve-18:temperature-limit': 0,
                         'device-settings:ls336:curve-19:temperature-limit': 0,
                         'device-settings:ls336:curve-20:temperature-limit': 0,
                         'device-settings:ls336:curve-21:temperature-limit': 0,
                         'device-settings:ls336:curve-22:temperature-limit': 0,
                         'device-settings:ls336:curve-23:temperature-limit': 0,
                         'device-settings:ls336:curve-24:temperature-limit': 0,
                         'device-settings:ls336:curve-25:temperature-limit': 0,
                         'device-settings:ls336:curve-26:temperature-limit': 0,
                         'device-settings:ls336:curve-27:temperature-limit': 0,
                         'device-settings:ls336:curve-28:temperature-limit': 0,
                         'device-settings:ls336:curve-29:temperature-limit': 0,
                         'device-settings:ls336:curve-30:temperature-limit': 0,
                         'device-settings:ls336:curve-31:temperature-limit': 0,
                         'device-settings:ls336:curve-32:temperature-limit': 0,
                         'device-settings:ls336:curve-33:temperature-limit': 0,
                         'device-settings:ls336:curve-34:temperature-limit': 0,
                         'device-settings:ls336:curve-35:temperature-limit': 0,
                         'device-settings:ls336:curve-36:temperature-limit': 0,
                         'device-settings:ls336:curve-37:temperature-limit': 0,
                         'device-settings:ls336:curve-38:temperature-limit': 0,
                         'device-settings:ls336:curve-39:temperature-limit': 0,
                         'device-settings:ls336:curve-40:temperature-limit': 0,
                         'device-settings:ls336:curve-41:temperature-limit': 0,
                         'device-settings:ls336:curve-42:temperature-limit': 0,
                         'device-settings:ls336:curve-43:temperature-limit': 0,
                         'device-settings:ls336:curve-44:temperature-limit': 0,
                         'device-settings:ls336:curve-45:temperature-limit': 0,
                         'device-settings:ls336:curve-46:temperature-limit': 0,
                         'device-settings:ls336:curve-47:temperature-limit': 0,
                         'device-settings:ls336:curve-48:temperature-limit': 0,
                         'device-settings:ls336:curve-49:temperature-limit': 0,
                         'device-settings:ls336:curve-50:temperature-limit': 0,
                         'device-settings:ls336:curve-51:temperature-limit': 0,
                         'device-settings:ls336:curve-52:temperature-limit': 0,
                         'device-settings:ls336:curve-53:temperature-limit': 0,
                         'device-settings:ls336:curve-54:temperature-limit': 0,
                         'device-settings:ls336:curve-55:temperature-limit': 0,
                         'device-settings:ls336:curve-56:temperature-limit': 0,
                         'device-settings:ls336:curve-57:temperature-limit': 0,
                         'device-settings:ls336:curve-58:temperature-limit': 0,
                         'device-settings:ls336:curve-59:temperature-limit': 0,
                         'device-settings:ls336:curve-21:coefficient': 'Positive',
                         'device-settings:ls336:curve-22:coefficient': 'Negative',
                         'device-settings:ls336:curve-23:coefficient': 'Negative',
                         'device-settings:ls336:curve-24:coefficient': 'Negative',
                         'device-settings:ls336:curve-25:coefficient': 'Negative',
                         'device-settings:ls336:curve-26:coefficient': 'Negative',
                         'device-settings:ls336:curve-27:coefficient': 'Negative',
                         'device-settings:ls336:curve-28:coefficient': 'Negative',
                         'device-settings:ls336:curve-29:coefficient': 'Negative',
                         'device-settings:ls336:curve-30:coefficient': 'Negative',
                         'device-settings:ls336:curve-31:coefficient': 'Negative',
                         'device-settings:ls336:curve-32:coefficient': 'Negative',
                         'device-settings:ls336:curve-33:coefficient': 'Negative',
                         'device-settings:ls336:curve-34:coefficient': 'Negative',
                         'device-settings:ls336:curve-35:coefficient': 'Negative',
                         'device-settings:ls336:curve-36:coefficient': 'Negative',
                         'device-settings:ls336:curve-37:coefficient': 'Negative',
                         'device-settings:ls336:curve-38:coefficient': 'Negative',
                         'device-settings:ls336:curve-39:coefficient': 'Negative',
                         'device-settings:ls336:curve-40:coefficient': 'Negative',
                         'device-settings:ls336:curve-41:coefficient': 'Negative',
                         'device-settings:ls336:curve-42:coefficient': 'Negative',
                         'device-settings:ls336:curve-43:coefficient': 'Negative',
                         'device-settings:ls336:curve-44:coefficient': 'Negative',
                         'device-settings:ls336:curve-45:coefficient': 'Negative',
                         'device-settings:ls336:curve-46:coefficient': 'Negative',
                         'device-settings:ls336:curve-47:coefficient': 'Negative',
                         'device-settings:ls336:curve-48:coefficient': 'Negative',
                         'device-settings:ls336:curve-49:coefficient': 'Negative',
                         'device-settings:ls336:curve-50:coefficient': 'Negative',
                         'device-settings:ls336:curve-51:coefficient': 'Negative',
                         'device-settings:ls336:curve-52:coefficient': 'Negative',
                         'device-settings:ls336:curve-53:coefficient': 'Negative',
                         'device-settings:ls336:curve-54:coefficient': 'Negative',
                         'device-settings:ls336:curve-55:coefficient': 'Negative',
                         'device-settings:ls336:curve-56:coefficient': 'Negative',
                         'device-settings:ls336:curve-57:coefficient': 'Negative',
                         'device-settings:ls336:curve-58:coefficient': 'Negative',
                         'device-settings:ls336:curve-59:coefficient': 'Negative',
                         'device-settings:ls372:input-channel-a:name': 'Device',
                         'device-settings:ls372:input-channel-1:name': '1K RTD',
                         'device-settings:ls372:input-channel-2:name': '',
                         'device-settings:ls372:input-channel-3:name': '',
                         'device-settings:ls372:input-channel-4:name': '',
                         'device-settings:ls372:input-channel-5:name': '',
                         'device-settings:ls372:input-channel-6:name': '',
                         'device-settings:ls372:input-channel-7:name': '',
                         'device-settings:ls372:input-channel-8:name': '',
                         'device-settings:ls372:input-channel-9:name': '',
                         'device-settings:ls372:input-channel-10:name': '',
                         'device-settings:ls372:input-channel-11:name': '',
                         'device-settings:ls372:input-channel-12:name': '',
                         'device-settings:ls372:input-channel-13:name': '',
                         'device-settings:ls372:input-channel-14:name': '',
                         'device-settings:ls372:input-channel-15:name': '',
                         'device-settings:ls372:input-channel-16:name': '',
                         'device-settings:ls372:input-channel-a:mode': 'Current',
                         'device-settings:ls372:input-channel-1:mode': 'Current',
                         'device-settings:ls372:input-channel-2:mode': 'Current',
                         'device-settings:ls372:input-channel-3:mode': 'Current',
                         'device-settings:ls372:input-channel-4:mode': 'Current',
                         'device-settings:ls372:input-channel-5:mode': 'Current',
                         'device-settings:ls372:input-channel-6:mode': 'Current',
                         'device-settings:ls372:input-channel-7:mode': 'Current',
                         'device-settings:ls372:input-channel-8:mode': 'Current',
                         'device-settings:ls372:input-channel-9:mode': 'Current',
                         'device-settings:ls372:input-channel-10:mode': 'Current',
                         'device-settings:ls372:input-channel-11:mode': 'Current',
                         'device-settings:ls372:input-channel-12:mode': 'Current',
                         'device-settings:ls372:input-channel-13:mode': 'Current',
                         'device-settings:ls372:input-channel-14:mode': 'Current',
                         'device-settings:ls372:input-channel-15:mode': 'Current',
                         'device-settings:ls372:input-channel-16:mode': 'Current',
                         'device-settings:ls372:input-channel-a:excitation-range': '1 nA',
                         'device-settings:ls372:input-channel-1:excitation-range': '1 nA',
                         'device-settings:ls372:input-channel-2:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-3:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-4:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-5:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-6:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-7:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-8:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-9:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-10:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-11:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-12:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-13:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-14:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-15:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-16:excitation-range': '10 pA',
                         'device-settings:ls372:input-channel-a:auto-range': 'Off',
                         'device-settings:ls372:input-channel-1:auto-range': 'Off',
                         'device-settings:ls372:input-channel-2:auto-range': 'Off',
                         'device-settings:ls372:input-channel-3:auto-range': 'Off',
                         'device-settings:ls372:input-channel-4:auto-range': 'Off',
                         'device-settings:ls372:input-channel-5:auto-range': 'Off',
                         'device-settings:ls372:input-channel-6:auto-range': 'Off',
                         'device-settings:ls372:input-channel-7:auto-range': 'Off',
                         'device-settings:ls372:input-channel-8:auto-range': 'Off',
                         'device-settings:ls372:input-channel-9:auto-range': 'Off',
                         'device-settings:ls372:input-channel-10:auto-range': 'Off',
                         'device-settings:ls372:input-channel-11:auto-range': 'Off',
                         'device-settings:ls372:input-channel-12:auto-range': 'Off',
                         'device-settings:ls372:input-channel-13:auto-range': 'Off',
                         'device-settings:ls372:input-channel-14:auto-range': 'Off',
                         'device-settings:ls372:input-channel-15:auto-range': 'Off',
                         'device-settings:ls372:input-channel-16:auto-range': 'Off',
                         'device-settings:ls372:input-channel-a:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-1:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-2:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-3:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-4:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-5:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-6:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-7:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-8:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-9:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-10:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-11:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-12:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-13:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-14:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-15:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-16:current-source-shunted': 'False',
                         'device-settings:ls372:input-channel-a:units': 'Kelvin',
                         'device-settings:ls372:input-channel-1:units': 'Kelvin',
                         'device-settings:ls372:input-channel-2:units': 'Kelvin',
                         'device-settings:ls372:input-channel-3:units': 'Kelvin',
                         'device-settings:ls372:input-channel-4:units': 'Kelvin',
                         'device-settings:ls372:input-channel-5:units': 'Kelvin',
                         'device-settings:ls372:input-channel-6:units': 'Kelvin',
                         'device-settings:ls372:input-channel-7:units': 'Kelvin',
                         'device-settings:ls372:input-channel-8:units': 'Kelvin',
                         'device-settings:ls372:input-channel-9:units': 'Kelvin',
                         'device-settings:ls372:input-channel-10:units': 'Kelvin',
                         'device-settings:ls372:input-channel-11:units': 'Kelvin',
                         'device-settings:ls372:input-channel-12:units': 'Kelvin',
                         'device-settings:ls372:input-channel-13:units': 'Kelvin',
                         'device-settings:ls372:input-channel-14:units': 'Kelvin',
                         'device-settings:ls372:input-channel-15:units': 'Kelvin',
                         'device-settings:ls372:input-channel-16:units': 'Kelvin',
                         'device-settings:ls372:input-channel-a:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-1:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-2:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-3:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-4:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-5:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-6:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-7:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-8:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-9:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-10:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-11:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-12:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-13:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-14:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-15:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-16:resistance-range': '62.3 k\u03A9',
                         'device-settings:ls372:input-channel-a:enable': 'True',
                         'device-settings:ls372:input-channel-1:enable': 'True',
                         'device-settings:ls372:input-channel-2:enable': 'False',
                         'device-settings:ls372:input-channel-3:enable': 'False',
                         'device-settings:ls372:input-channel-4:enable': 'False',
                         'device-settings:ls372:input-channel-5:enable': 'False',
                         'device-settings:ls372:input-channel-6:enable': 'False',
                         'device-settings:ls372:input-channel-7:enable': 'False',
                         'device-settings:ls372:input-channel-8:enable': 'False',
                         'device-settings:ls372:input-channel-9:enable': 'False',
                         'device-settings:ls372:input-channel-10:enable': 'False',
                         'device-settings:ls372:input-channel-11:enable': 'False',
                         'device-settings:ls372:input-channel-12:enable': 'False',
                         'device-settings:ls372:input-channel-13:enable': 'False',
                         'device-settings:ls372:input-channel-14:enable': 'False',
                         'device-settings:ls372:input-channel-15:enable': 'False',
                         'device-settings:ls372:input-channel-16:enable': 'False',
                         'device-settings:ls372:input-channel-a:dwell-time': 0,
                         'device-settings:ls372:input-channel-1:dwell-time': 0,
                         'device-settings:ls372:input-channel-2:dwell-time': 0,
                         'device-settings:ls372:input-channel-3:dwell-time': 0,
                         'device-settings:ls372:input-channel-4:dwell-time': 0,
                         'device-settings:ls372:input-channel-5:dwell-time': 0,
                         'device-settings:ls372:input-channel-6:dwell-time': 0,
                         'device-settings:ls372:input-channel-7:dwell-time': 0,
                         'device-settings:ls372:input-channel-8:dwell-time': 0,
                         'device-settings:ls372:input-channel-9:dwell-time': 0,
                         'device-settings:ls372:input-channel-10:dwell-time': 0,
                         'device-settings:ls372:input-channel-11:dwell-time': 0,
                         'device-settings:ls372:input-channel-12:dwell-time': 0,
                         'device-settings:ls372:input-channel-13:dwell-time': 0,
                         'device-settings:ls372:input-channel-14:dwell-time': 0,
                         'device-settings:ls372:input-channel-15:dwell-time': 0,
                         'device-settings:ls372:input-channel-16:dwell-time': 0,
                         'device-settings:ls372:input-channel-a:pause-time': 3,
                         'device-settings:ls372:input-channel-1:pause-time': 3,
                         'device-settings:ls372:input-channel-2:pause-time': 3,
                         'device-settings:ls372:input-channel-3:pause-time': 3,
                         'device-settings:ls372:input-channel-4:pause-time': 3,
                         'device-settings:ls372:input-channel-5:pause-time': 3,
                         'device-settings:ls372:input-channel-6:pause-time': 3,
                         'device-settings:ls372:input-channel-7:pause-time': 3,
                         'device-settings:ls372:input-channel-8:pause-time': 3,
                         'device-settings:ls372:input-channel-9:pause-time': 3,
                         'device-settings:ls372:input-channel-10:pause-time': 3,
                         'device-settings:ls372:input-channel-11:pause-time': 3,
                         'device-settings:ls372:input-channel-12:pause-time': 3,
                         'device-settings:ls372:input-channel-13:pause-time': 3,
                         'device-settings:ls372:input-channel-14:pause-time': 3,
                         'device-settings:ls372:input-channel-15:pause-time': 3,
                         'device-settings:ls372:input-channel-16:pause-time': 3,
                         'device-settings:ls372:input-channel-a:curve-number': 8,
                         'device-settings:ls372:input-channel-1:curve-number': 8,
                         'device-settings:ls372:input-channel-2:curve-number': 8,
                         'device-settings:ls372:input-channel-3:curve-number': 8,
                         'device-settings:ls372:input-channel-4:curve-number': 8,
                         'device-settings:ls372:input-channel-5:curve-number': 8,
                         'device-settings:ls372:input-channel-6:curve-number': 8,
                         'device-settings:ls372:input-channel-7:curve-number': 8,
                         'device-settings:ls372:input-channel-8:curve-number': 8,
                         'device-settings:ls372:input-channel-9:curve-number': 8,
                         'device-settings:ls372:input-channel-10:curve-number': 8,
                         'device-settings:ls372:input-channel-11:curve-number': 8,
                         'device-settings:ls372:input-channel-12:curve-number': 8,
                         'device-settings:ls372:input-channel-13:curve-number': 8,
                         'device-settings:ls372:input-channel-14:curve-number': 8,
                         'device-settings:ls372:input-channel-15:curve-number': 8,
                         'device-settings:ls372:input-channel-16:curve-number': 8,
                         'device-settings:ls372:input-channel-a:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-1:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-2:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-3:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-4:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-5:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-6:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-7:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-8:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-9:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-10:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-11:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-12:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-13:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-14:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-15:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-16:temperature-coefficient': 'Negative',
                         'device-settings:ls372:input-channel-a:filter:state': 'On',
                         'device-settings:ls372:input-channel-1:filter:state': 'Off',
                         'device-settings:ls372:input-channel-2:filter:state': 'Off',
                         'device-settings:ls372:input-channel-3:filter:state': 'Off',
                         'device-settings:ls372:input-channel-4:filter:state': 'Off',
                         'device-settings:ls372:input-channel-5:filter:state': 'Off',
                         'device-settings:ls372:input-channel-6:filter:state': 'Off',
                         'device-settings:ls372:input-channel-7:filter:state': 'Off',
                         'device-settings:ls372:input-channel-8:filter:state': 'Off',
                         'device-settings:ls372:input-channel-9:filter:state': 'Off',
                         'device-settings:ls372:input-channel-10:filter:state': 'Off',
                         'device-settings:ls372:input-channel-11:filter:state': 'Off',
                         'device-settings:ls372:input-channel-12:filter:state': 'Off',
                         'device-settings:ls372:input-channel-13:filter:state': 'Off',
                         'device-settings:ls372:input-channel-14:filter:state': 'Off',
                         'device-settings:ls372:input-channel-15:filter:state': 'Off',
                         'device-settings:ls372:input-channel-16:filter:state': 'Off',
                         'device-settings:ls372:input-channel-a:filter:settle-time': 5,
                         'device-settings:ls372:input-channel-1:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-2:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-3:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-4:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-5:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-6:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-7:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-8:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-9:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-10:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-11:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-12:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-13:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-14:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-15:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-16:filter:settle-time': 1,
                         'device-settings:ls372:input-channel-a:filter:window': 10,
                         'device-settings:ls372:input-channel-1:filter:window': 1,
                         'device-settings:ls372:input-channel-2:filter:window': 1,
                         'device-settings:ls372:input-channel-3:filter:window': 1,
                         'device-settings:ls372:input-channel-4:filter:window': 1,
                         'device-settings:ls372:input-channel-5:filter:window': 1,
                         'device-settings:ls372:input-channel-6:filter:window': 1,
                         'device-settings:ls372:input-channel-7:filter:window': 1,
                         'device-settings:ls372:input-channel-8:filter:window': 1,
                         'device-settings:ls372:input-channel-9:filter:window': 1,
                         'device-settings:ls372:input-channel-10:filter:window': 1,
                         'device-settings:ls372:input-channel-11:filter:window': 1,
                         'device-settings:ls372:input-channel-12:filter:window': 1,
                         'device-settings:ls372:input-channel-13:filter:window': 1,
                         'device-settings:ls372:input-channel-14:filter:window': 1,
                         'device-settings:ls372:input-channel-15:filter:window': 1,
                         'device-settings:ls372:input-channel-16:filter:window': 1,
                         'device-settings:ls372:heater-channel-0:output-mode': 'Closed Loop',
                         'device-settings:ls372:heater-channel-1:output-mode': 'Off',
                         'device-settings:ls372:heater-channel-2:output-mode': 'Off',
                         'device-settings:ls372:heater-channel-0:input-channel': 'Control',
                         'device-settings:ls372:heater-channel-1:input-channel': 'Control',
                         'device-settings:ls372:heater-channel-2:input-channel': 'Control',
                         'device-settings:ls372:heater-channel-0:powerup-enable': 'False',
                         'device-settings:ls372:heater-channel-1:powerup-enable': 'False',
                         'device-settings:ls372:heater-channel-2:powerup-enable': 'False',
                         'device-settings:ls372:heater-channel-0:reading-filter': 'True',
                         'device-settings:ls372:heater-channel-1:reading-filter': 'False',
                         'device-settings:ls372:heater-channel-2:reading-filter': 'False',
                         'device-settings:ls372:heater-channel-0:delay': 1,
                         'device-settings:ls372:heater-channel-1:delay': 1,
                         'device-settings:ls372:heater-channel-2:delay': 1,
                         'device-settings:ls372:heater-channel-0:polarity': 'Unipolar',
                         'device-settings:ls372:heater-channel-1:polarity': 'Unipolar',
                         'device-settings:ls372:heater-channel-2:polarity': 'Unipolar',
                         'device-settings:ls372:heater-channel-0:setpoint': 0.090,
                         'device-settings:ls372:heater-channel-1:setpoint': 4,
                         'device-settings:ls372:heater-channel-2:setpoint': 4,
                         'device-settings:ls372:heater-channel-0:gain': 12.950,
                         'device-settings:ls372:heater-channel-1:gain': 0.0,
                         'device-settings:ls372:heater-channel-2:gain': 0.0,
                         'device-settings:ls372:heater-channel-0:integral': 9.0,
                         'device-settings:ls372:heater-channel-1:integral': 0.0,
                         'device-settings:ls372:heater-channel-2:integral': 0.0,
                         'device-settings:ls372:heater-channel-0:ramp_rate': 0.1,
                         'device-settings:ls372:heater-channel-1:ramp_rate': 0.0,
                         'device-settings:ls372:heater-channel-2:ramp_rate': 0.0,
                         'device-settings:ls372:heater-channel-0:range': '1 mA',
                         'device-settings:ls372:heater-channel-1:range': 'Off',
                         'device-settings:ls372:heater-channel-2:range': 'Off',
                         'device-settings:ls372:curve-21:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-22:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-23:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-24:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-25:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-26:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-27:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-28:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-29:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-30:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-31:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-32:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-33:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-34:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-35:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-36:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-37:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-38:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-39:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-40:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-41:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-42:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-43:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-44:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-45:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-46:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-47:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-48:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-49:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-50:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-51:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-52:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-53:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-54:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-55:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-56:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-57:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-58:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-59:curve-name': 'User Curve     ',
                         'device-settings:ls372:curve-21:serial-number': '          ',
                         'device-settings:ls372:curve-22:serial-number': '          ',
                         'device-settings:ls372:curve-23:serial-number': '          ',
                         'device-settings:ls372:curve-24:serial-number': '          ',
                         'device-settings:ls372:curve-25:serial-number': '          ',
                         'device-settings:ls372:curve-26:serial-number': '          ',
                         'device-settings:ls372:curve-27:serial-number': '          ',
                         'device-settings:ls372:curve-28:serial-number': '          ',
                         'device-settings:ls372:curve-29:serial-number': '          ',
                         'device-settings:ls372:curve-30:serial-number': '          ',
                         'device-settings:ls372:curve-31:serial-number': '          ',
                         'device-settings:ls372:curve-32:serial-number': '          ',
                         'device-settings:ls372:curve-33:serial-number': '          ',
                         'device-settings:ls372:curve-34:serial-number': '          ',
                         'device-settings:ls372:curve-35:serial-number': '          ',
                         'device-settings:ls372:curve-36:serial-number': '          ',
                         'device-settings:ls372:curve-37:serial-number': '          ',
                         'device-settings:ls372:curve-38:serial-number': '          ',
                         'device-settings:ls372:curve-39:serial-number': '          ',
                         'device-settings:ls372:curve-40:serial-number': '          ',
                         'device-settings:ls372:curve-41:serial-number': '          ',
                         'device-settings:ls372:curve-42:serial-number': '          ',
                         'device-settings:ls372:curve-43:serial-number': '          ',
                         'device-settings:ls372:curve-44:serial-number': '          ',
                         'device-settings:ls372:curve-45:serial-number': '          ',
                         'device-settings:ls372:curve-46:serial-number': '          ',
                         'device-settings:ls372:curve-47:serial-number': '          ',
                         'device-settings:ls372:curve-48:serial-number': '          ',
                         'device-settings:ls372:curve-49:serial-number': '          ',
                         'device-settings:ls372:curve-50:serial-number': '          ',
                         'device-settings:ls372:curve-51:serial-number': '          ',
                         'device-settings:ls372:curve-52:serial-number': '          ',
                         'device-settings:ls372:curve-53:serial-number': '          ',
                         'device-settings:ls372:curve-54:serial-number': '          ',
                         'device-settings:ls372:curve-55:serial-number': '          ',
                         'device-settings:ls372:curve-56:serial-number': '          ',
                         'device-settings:ls372:curve-57:serial-number': '          ',
                         'device-settings:ls372:curve-58:serial-number': '          ',
                         'device-settings:ls372:curve-59:serial-number': '          ',
                         'device-settings:ls372:curve-21:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-22:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-23:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-24:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-25:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-26:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-27:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-28:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-29:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-30:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-31:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-32:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-33:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-34:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-35:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-36:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-37:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-38:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-39:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-40:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-41:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-42:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-43:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-44:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-45:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-46:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-47:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-48:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-49:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-50:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-51:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-52:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-53:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-54:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-55:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-56:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-57:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-58:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-59:curve-data-format': '\u03A9/K',
                         'device-settings:ls372:curve-1:temperature-limit': 0,
                         'device-settings:ls372:curve-2:temperature-limit': 0,
                         'device-settings:ls372:curve-3:temperature-limit': 0,
                         'device-settings:ls372:curve-4:temperature-limit': 0,
                         'device-settings:ls372:curve-5:temperature-limit': 0,
                         'device-settings:ls372:curve-6:temperature-limit': 0,
                         'device-settings:ls372:curve-7:temperature-limit': 0,
                         'device-settings:ls372:curve-8:temperature-limit': 0,
                         'device-settings:ls372:curve-9:temperature-limit': 0,
                         'device-settings:ls372:curve-10:temperature-limit': 0,
                         'device-settings:ls372:curve-11:temperature-limit': 0,
                         'device-settings:ls372:curve-12:temperature-limit': 0,
                         'device-settings:ls372:curve-13:temperature-limit': 0,
                         'device-settings:ls372:curve-14:temperature-limit': 0,
                         'device-settings:ls372:curve-15:temperature-limit': 0,
                         'device-settings:ls372:curve-16:temperature-limit': 0,
                         'device-settings:ls372:curve-17:temperature-limit': 0,
                         'device-settings:ls372:curve-18:temperature-limit': 0,
                         'device-settings:ls372:curve-19:temperature-limit': 0,
                         'device-settings:ls372:curve-20:temperature-limit': 0,
                         'device-settings:ls372:curve-21:temperature-limit': 0,
                         'device-settings:ls372:curve-22:temperature-limit': 0,
                         'device-settings:ls372:curve-23:temperature-limit': 0,
                         'device-settings:ls372:curve-24:temperature-limit': 0,
                         'device-settings:ls372:curve-25:temperature-limit': 0,
                         'device-settings:ls372:curve-26:temperature-limit': 0,
                         'device-settings:ls372:curve-27:temperature-limit': 0,
                         'device-settings:ls372:curve-28:temperature-limit': 0,
                         'device-settings:ls372:curve-29:temperature-limit': 0,
                         'device-settings:ls372:curve-30:temperature-limit': 0,
                         'device-settings:ls372:curve-31:temperature-limit': 0,
                         'device-settings:ls372:curve-32:temperature-limit': 0,
                         'device-settings:ls372:curve-33:temperature-limit': 0,
                         'device-settings:ls372:curve-34:temperature-limit': 0,
                         'device-settings:ls372:curve-35:temperature-limit': 0,
                         'device-settings:ls372:curve-36:temperature-limit': 0,
                         'device-settings:ls372:curve-37:temperature-limit': 0,
                         'device-settings:ls372:curve-38:temperature-limit': 0,
                         'device-settings:ls372:curve-39:temperature-limit': 0,
                         'device-settings:ls372:curve-40:temperature-limit': 0,
                         'device-settings:ls372:curve-41:temperature-limit': 0,
                         'device-settings:ls372:curve-42:temperature-limit': 0,
                         'device-settings:ls372:curve-43:temperature-limit': 0,
                         'device-settings:ls372:curve-44:temperature-limit': 0,
                         'device-settings:ls372:curve-45:temperature-limit': 0,
                         'device-settings:ls372:curve-46:temperature-limit': 0,
                         'device-settings:ls372:curve-47:temperature-limit': 0,
                         'device-settings:ls372:curve-48:temperature-limit': 0,
                         'device-settings:ls372:curve-49:temperature-limit': 0,
                         'device-settings:ls372:curve-50:temperature-limit': 0,
                         'device-settings:ls372:curve-51:temperature-limit': 0,
                         'device-settings:ls372:curve-52:temperature-limit': 0,
                         'device-settings:ls372:curve-53:temperature-limit': 0,
                         'device-settings:ls372:curve-54:temperature-limit': 0,
                         'device-settings:ls372:curve-55:temperature-limit': 0,
                         'device-settings:ls372:curve-56:temperature-limit': 0,
                         'device-settings:ls372:curve-57:temperature-limit': 0,
                         'device-settings:ls372:curve-58:temperature-limit': 0,
                         'device-settings:ls372:curve-59:temperature-limit': 0,
                         'device-settings:ls372:curve-21:coefficient': 'Negative',
                         'device-settings:ls372:curve-22:coefficient': 'Negative',
                         'device-settings:ls372:curve-23:coefficient': 'Negative',
                         'device-settings:ls372:curve-24:coefficient': 'Negative',
                         'device-settings:ls372:curve-25:coefficient': 'Negative',
                         'device-settings:ls372:curve-26:coefficient': 'Negative',
                         'device-settings:ls372:curve-27:coefficient': 'Negative',
                         'device-settings:ls372:curve-28:coefficient': 'Negative',
                         'device-settings:ls372:curve-29:coefficient': 'Negative',
                         'device-settings:ls372:curve-30:coefficient': 'Negative',
                         'device-settings:ls372:curve-31:coefficient': 'Negative',
                         'device-settings:ls372:curve-32:coefficient': 'Negative',
                         'device-settings:ls372:curve-33:coefficient': 'Negative',
                         'device-settings:ls372:curve-34:coefficient': 'Negative',
                         'device-settings:ls372:curve-35:coefficient': 'Negative',
                         'device-settings:ls372:curve-36:coefficient': 'Negative',
                         'device-settings:ls372:curve-37:coefficient': 'Negative',
                         'device-settings:ls372:curve-38:coefficient': 'Negative',
                         'device-settings:ls372:curve-39:coefficient': 'Negative',
                         'device-settings:ls372:curve-40:coefficient': 'Negative',
                         'device-settings:ls372:curve-41:coefficient': 'Negative',
                         'device-settings:ls372:curve-42:coefficient': 'Negative',
                         'device-settings:ls372:curve-43:coefficient': 'Negative',
                         'device-settings:ls372:curve-44:coefficient': 'Negative',
                         'device-settings:ls372:curve-45:coefficient': 'Negative',
                         'device-settings:ls372:curve-46:coefficient': 'Negative',
                         'device-settings:ls372:curve-47:coefficient': 'Negative',
                         'device-settings:ls372:curve-48:coefficient': 'Negative',
                         'device-settings:ls372:curve-49:coefficient': 'Negative',
                         'device-settings:ls372:curve-50:coefficient': 'Negative',
                         'device-settings:ls372:curve-51:coefficient': 'Negative',
                         'device-settings:ls372:curve-52:coefficient': 'Negative',
                         'device-settings:ls372:curve-53:coefficient': 'Negative',
                         'device-settings:ls372:curve-54:coefficient': 'Negative',
                         'device-settings:ls372:curve-55:coefficient': 'Negative',
                         'device-settings:ls372:curve-56:coefficient': 'Negative',
                         'device-settings:ls372:curve-57:coefficient': 'Negative',
                         'device-settings:ls372:curve-58:coefficient': 'Negative',
                         'device-settings:ls372:curve-59:coefficient': 'Negative',
                         'device-settings:ls625:baud-rate': 9600,
                         'device-settings:ls625:current-limit': 10.0,
                         'device-settings:ls625:compliance-voltage-limit': 2.5,
                         'device-settings:ls625:rate-limit': 1.000,
                         'device-settings:ls625:magnetic-field-parameter': 4.0609,
                         'device-settings:ls625:quench-ramp-rate': 1.000,
                         'device-settings:ls625:ramp-rate': 0.005,
                         'device-settings:ls625:desired-current': 0.0,
                         'device-settings:ls625:compliance-voltage': 2.5,
                         'device-settings:ls625:control-mode': 'Sum',
                         'device-settings:heatswitch:position': 'Close',
                         'device-settings:heatswitch:max-velocity': '1000.0',
                         'device-settings:heatswitch:running-current': '13',
                         'device-settings:heatswitch:acceleration': '2',
                         'device-settings:laserflipperduino:laserbox:808:power': 0,
                         'device-settings:laserflipperduino:laserbox:904:power': 0,
                         'device-settings:laserflipperduino:laserbox:980:power': 0,
                         'device-settings:laserflipperduino:laserbox:1120:power': 0,
                         'device-settings:laserflipperduino:laserbox:1310:power': 0,
                         'device-settings:laserflipperduino:flipper:position': "Down",
                         'device-settings:filterwheel:position': '0',
                         'device-settings:focus:home-params:velocity': 137439,
                         'device-settings:focus:home-params:offset-distance': 0,
                         'device-settings:focus:home-params:direction': 'Reverse',
                         'device-settings:focus:jog-params:size': 2458,
                         'device-settings:focus:jog-params:acceleration': 75,
                         'device-settings:focus:jog-params:max-velocity': 164931,
                         'device-settings:focus:jog-params:continuous': 'False',
                         'device-settings:focus:move-params:backlash-distance': 246,
                         'device-settings:focus:velocity-params:acceleration': 75,
                         'device-settings:focus:velocity-params:max-velocity': 164931,
                         'device-settings:focus:desired-position:encoder': 0,
                         'device-settings:magnet:ramp-rate': 0.005,
                         'device-settings:magnet:deramp-rate': 0.005,
                         'device-settings:magnet:soak-time': 3600,  # Always in seconds
                         'device-settings:magnet:soak-current': 9.25,
                         'device-settings:mkidarray:regulating-temp': 0.090,
                         'device-settings:conex:move-retries': 5
                         }
                }


# REDIS_SCHEMA['keys'].update(effects)


def schema_keys():
    return tuple(REDIS_SCHEMA['keys'].keys())


basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(pkg_resources.resource_filename('mkidcontrol', '../configuration/mkidcontrol.env'))


class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite:///' + os.path.join(basedir,
                                                                                            'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    LOG_TO_STDOUT = os.environ.get('LOG_TO_STDOUT')
    MAIL_SERVER = os.environ.get('MAIL_SERVER')
    # if int(os.environ.get('MAIL_PORT')):
    #     MAIL_PORT = int(os.environ.get('MAIL_PORT'))
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() == 'true'
    MAIL_USE_SSL = os.environ.get('MAIL_USE_SSL', 'false').lower() == 'true'
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    ADMINS = ['bmazin@ucsb.edu', 'baileyji@ucsb.edu', 'nswimmer@ucsb.edu']
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', True)
    XKID_BASE_DIR = "/data/XKID"

    FLASK_RUN_HOST = '0.0.0.0'
    FLASK_RUN_PORT = 8000
    LANGUAGES = ['en']
    REDIS_URL = os.environ.get('REDIS_URL') or 'redis://'
    POSTS_PER_PAGE = 25
