# What fraction of FULL ON (512 leds @ white, max brightness) can we manage.
#  Do not increase this above what the PSU can deliver or the cloud LED PSU will
#  overcurrent and shut it self off.
#  The cloud idles at 6 Watts and 256 full on uses 60 W. Implies full LED array uses 108W
#  PSU can drive 90W, so 90/108 -> 0.8333. Use 0.8 as that's pretty bright and adds some margin.
import json
import pkg_resources
import os
from dotenv import load_dotenv

REDIS_DB = 0

REDIS_TS_RETENTION = 60 * 60 * 1000  # 30 min

REDIS_TS_KEYS = ('temp:value', 'temp:cpu:value', 'lamp:flux'
                 'speaker:level', 'mic:level')

REDIS_SCHEMA = {'timeseries': {k: REDIS_TS_RETENTION for k in REDIS_TS_KEYS},
                'channels': ('lamp:settings',
                             'player:melody:play',
                             'player:effect:play',
                             'player:melody:stop',
                             'player:effect:stop'),
                'keys': {'device-settings:ls336:input-channel-a:sensor-type': 'Disabled',
                         'device-settings:ls336:input-channel-b:sensor-type': 'NTC RTD',
                         'device-settings:ls336:input-channel-c:sensor-type': 'Diode',
                         'device-settings:ls336:input-channel-d:sensor-type': 'Diode',
                         'device-settings:ls336:input-channel-a:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-b:autorange-enable': 'True',
                         'device-settings:ls336:input-channel-c:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-d:autorange-enable': 'False',
                         'device-settings:ls336:input-channel-a:compensation': 'False',
                         'device-settings:ls336:input-channel-b:compensation': 'False',
                         'device-settings:ls336:input-channel-c:compensation': 'False',
                         'device-settings:ls336:input-channel-d:compensation': 'False',
                         'device-settings:ls336:input-channel-a:units': 'Kelving',
                         'device-settings:ls336:input-channel-b:units': 'Kelvin',
                         'device-settings:ls336:input-channel-c:units': 'Kelvin',
                         'device-settings:ls336:input-channel-d:units': 'Kelvin',
                         'device-settings:ls336:input-channel-a:input-range': '30000.0 \u03A9',
                         'device-settings:ls336:input-channel-b:input-range': '30000.0 \u03A9',
                         'device-settings:ls336:input-channel-c:input-range': '2.5 V',
                         'device-settings:ls336:input-channel-d:input-range': '2.5 V',
                         'device-settings:ls336:input-channel-a:curve': 8,
                         'device-settings:ls336:input-channel-b:curve': 8,
                         'device-settings:ls336:input-channel-c:curve': 2,
                         'device-settings:ls336:input-channel-d:curve': 2,
                         'device-settings:ls336:curve-21:curve-name': 'RO600          ',
                         'device-settings:ls336:curve-22:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-23:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-24:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-25:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-26:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-27:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-28:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-29:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-30:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-31:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-32:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-33:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-34:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-35:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-36:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-37:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-38:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-39:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-40:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-41:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-42:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-43:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-44:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-45:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-46:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-47:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-48:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-49:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-50:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-51:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-52:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-53:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-54:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-55:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-56:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-57:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-58:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-59:curve-name': 'User Curve     ',
                         'device-settings:ls336:curve-21:serial-number': '3856      ',
                         'device-settings:ls336:curve-22:serial-number': '          ',
                         'device-settings:ls336:curve-23:serial-number': '          ',
                         'device-settings:ls336:curve-24:serial-number': '          ',
                         'device-settings:ls336:curve-25:serial-number': '          ',
                         'device-settings:ls336:curve-26:serial-number': '          ',
                         'device-settings:ls336:curve-27:serial-number': '          ',
                         'device-settings:ls336:curve-28:serial-number': '          ',
                         'device-settings:ls336:curve-29:serial-number': '          ',
                         'device-settings:ls336:curve-30:serial-number': '          ',
                         'device-settings:ls336:curve-31:serial-number': '          ',
                         'device-settings:ls336:curve-32:serial-number': '          ',
                         'device-settings:ls336:curve-33:serial-number': '          ',
                         'device-settings:ls336:curve-34:serial-number': '          ',
                         'device-settings:ls336:curve-35:serial-number': '          ',
                         'device-settings:ls336:curve-36:serial-number': '          ',
                         'device-settings:ls336:curve-37:serial-number': '          ',
                         'device-settings:ls336:curve-38:serial-number': '          ',
                         'device-settings:ls336:curve-39:serial-number': '          ',
                         'device-settings:ls336:curve-40:serial-number': '          ',
                         'device-settings:ls336:curve-41:serial-number': '          ',
                         'device-settings:ls336:curve-42:serial-number': '          ',
                         'device-settings:ls336:curve-43:serial-number': '          ',
                         'device-settings:ls336:curve-44:serial-number': '          ',
                         'device-settings:ls336:curve-45:serial-number': '          ',
                         'device-settings:ls336:curve-46:serial-number': '          ',
                         'device-settings:ls336:curve-47:serial-number': '          ',
                         'device-settings:ls336:curve-48:serial-number': '          ',
                         'device-settings:ls336:curve-49:serial-number': '          ',
                         'device-settings:ls336:curve-50:serial-number': '          ',
                         'device-settings:ls336:curve-51:serial-number': '          ',
                         'device-settings:ls336:curve-52:serial-number': '          ',
                         'device-settings:ls336:curve-53:serial-number': '          ',
                         'device-settings:ls336:curve-54:serial-number': '          ',
                         'device-settings:ls336:curve-55:serial-number': '          ',
                         'device-settings:ls336:curve-56:serial-number': '          ',
                         'device-settings:ls336:curve-57:serial-number': '          ',
                         'device-settings:ls336:curve-58:serial-number': '          ',
                         'device-settings:ls336:curve-59:serial-number': '          ',
                         'device-settings:ls336:curve-21:curve-data-format': 'OHMS_PER_KELVIN',
                         'device-settings:ls336:curve-22:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-23:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-24:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-25:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-26:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-27:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-28:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-29:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-30:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-31:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-32:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-33:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-34:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-35:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-36:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-37:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-38:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-39:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-40:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-41:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-42:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-43:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-44:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-45:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-46:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-47:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-48:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-49:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-50:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-51:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-52:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-53:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-54:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-55:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-56:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-57:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-58:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-59:curve-data-format': 'V/K',
                         'device-settings:ls336:curve-21:temperature-limit': '375.0',
                         'device-settings:ls336:curve-22:temperature-limit': '375.0',
                         'device-settings:ls336:curve-23:temperature-limit': '375.0',
                         'device-settings:ls336:curve-24:temperature-limit': '375.0',
                         'device-settings:ls336:curve-25:temperature-limit': '375.0',
                         'device-settings:ls336:curve-26:temperature-limit': '375.0',
                         'device-settings:ls336:curve-27:temperature-limit': '375.0',
                         'device-settings:ls336:curve-28:temperature-limit': '375.0',
                         'device-settings:ls336:curve-29:temperature-limit': '375.0',
                         'device-settings:ls336:curve-30:temperature-limit': '375.0',
                         'device-settings:ls336:curve-31:temperature-limit': '375.0',
                         'device-settings:ls336:curve-32:temperature-limit': '375.0',
                         'device-settings:ls336:curve-33:temperature-limit': '375.0',
                         'device-settings:ls336:curve-34:temperature-limit': '375.0',
                         'device-settings:ls336:curve-35:temperature-limit': '375.0',
                         'device-settings:ls336:curve-36:temperature-limit': '375.0',
                         'device-settings:ls336:curve-37:temperature-limit': '375.0',
                         'device-settings:ls336:curve-38:temperature-limit': '375.0',
                         'device-settings:ls336:curve-39:temperature-limit': '375.0',
                         'device-settings:ls336:curve-40:temperature-limit': '375.0',
                         'device-settings:ls336:curve-41:temperature-limit': '375.0',
                         'device-settings:ls336:curve-42:temperature-limit': '375.0',
                         'device-settings:ls336:curve-43:temperature-limit': '375.0',
                         'device-settings:ls336:curve-44:temperature-limit': '375.0',
                         'device-settings:ls336:curve-45:temperature-limit': '375.0',
                         'device-settings:ls336:curve-46:temperature-limit': '375.0',
                         'device-settings:ls336:curve-47:temperature-limit': '375.0',
                         'device-settings:ls336:curve-48:temperature-limit': '375.0',
                         'device-settings:ls336:curve-49:temperature-limit': '375.0',
                         'device-settings:ls336:curve-50:temperature-limit': '375.0',
                         'device-settings:ls336:curve-51:temperature-limit': '375.0',
                         'device-settings:ls336:curve-52:temperature-limit': '375.0',
                         'device-settings:ls336:curve-53:temperature-limit': '375.0',
                         'device-settings:ls336:curve-54:temperature-limit': '375.0',
                         'device-settings:ls336:curve-55:temperature-limit': '375.0',
                         'device-settings:ls336:curve-56:temperature-limit': '375.0',
                         'device-settings:ls336:curve-57:temperature-limit': '375.0',
                         'device-settings:ls336:curve-58:temperature-limit': '375.0',
                         'device-settings:ls336:curve-59:temperature-limit': '375.0',
                         'device-settings:ls336:curve-21:coefficient': 'Positive',
                         'device-settings:ls336:curve-22:coefficient': 'Negative',
                         'device-settings:ls336:curve-23:coefficient': 'Negative',
                         'device-settings:ls336:curve-24:coefficient': 'Negative',
                         'device-settings:ls336:curve-25:coefficient': 'Negative',
                         'device-settings:ls336:curve-26:coefficient': 'Negative',
                         'device-settings:ls336:curve-27:coefficient': 'Negative',
                         'device-settings:ls336:curve-28:coefficient': 'Negative',
                         'device-settings:ls336:curve-29:coefficient': 'Negative',
                         'device-settings:ls336:curve-30:coefficient': 'Negative',
                         'device-settings:ls336:curve-31:coefficient': 'Negative',
                         'device-settings:ls336:curve-32:coefficient': 'Negative',
                         'device-settings:ls336:curve-33:coefficient': 'Negative',
                         'device-settings:ls336:curve-34:coefficient': 'Negative',
                         'device-settings:ls336:curve-35:coefficient': 'Negative',
                         'device-settings:ls336:curve-36:coefficient': 'Negative',
                         'device-settings:ls336:curve-37:coefficient': 'Negative',
                         'device-settings:ls336:curve-38:coefficient': 'Negative',
                         'device-settings:ls336:curve-39:coefficient': 'Negative',
                         'device-settings:ls336:curve-40:coefficient': 'Negative',
                         'device-settings:ls336:curve-41:coefficient': 'Negative',
                         'device-settings:ls336:curve-42:coefficient': 'Negative',
                         'device-settings:ls336:curve-43:coefficient': 'Negative',
                         'device-settings:ls336:curve-44:coefficient': 'Negative',
                         'device-settings:ls336:curve-45:coefficient': 'Negative',
                         'device-settings:ls336:curve-46:coefficient': 'Negative',
                         'device-settings:ls336:curve-47:coefficient': 'Negative',
                         'device-settings:ls336:curve-48:coefficient': 'Negative',
                         'device-settings:ls336:curve-49:coefficient': 'Negative',
                         'device-settings:ls336:curve-50:coefficient': 'Negative',
                         'device-settings:ls336:curve-51:coefficient': 'Negative',
                         'device-settings:ls336:curve-52:coefficient': 'Negative',
                         'device-settings:ls336:curve-53:coefficient': 'Negative',
                         'device-settings:ls336:curve-54:coefficient': 'Negative',
                         'device-settings:ls336:curve-55:coefficient': 'Negative',
                         'device-settings:ls336:curve-56:coefficient': 'Negative',
                         'device-settings:ls336:curve-57:coefficient': 'Negative',
                         'device-settings:ls336:curve-58:coefficient': 'Negative',
                         'device-settings:ls336:curve-59:coefficient': 'Negative'}
                }
# effects = {f'lamp:{e.key}:settings': e.defaults for e in EffectData}
# REDIS_SCHEMA['keys'].update(effects)


def schema_keys():
    return tuple(REDIS_SCHEMA['keys'].keys())


basedir = os.path.abspath(os.path.dirname(__file__))
# load_dotenv(pkg_resources.resource_filename('cloudlight', '../config/cloudweb.env'))


class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite:///' + os.path.join(basedir,
                                                                                            'mkidDirector/app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    LOG_TO_STDOUT = os.environ.get('LOG_TO_STDOUT')
    MAIL_SERVER = os.environ.get('MAIL_SERVER')
    # if int(os.environ.get('MAIL_PORT')):
    #     MAIL_PORT = int(os.environ.get('MAIL_PORT'))
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() == 'true'
    MAIL_USE_SSL = os.environ.get('MAIL_USE_SSL', 'false').lower() == 'true'
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    ADMINS = ['baileyji@ucsb.edu']
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', True)

    FLASK_RUN_HOST = '0.0.0.0'
    FLASK_RUN_PORT = 8080
    LANGUAGES = ['en']
    REDIS_URL = os.environ.get('REDIS_URL') or 'redis://'
    POSTS_PER_PAGE = 25
