loggers:
  controlDirector:
    werkzeug: warning
    controlDirector:
      handlers: [ default ]
      level: DEBUG
      propagate: False
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  lakeshore240Agent: info
  currentduinoAgent:
    currentduinoAgent: debug
    mkidcontrol.mkidredis: info
    mkidcontrol.devices: debug
    serial: debug
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  hemttempAgent:
    hemttempAgent: debug
    mkidcontrol.mkidredis: info
  heatswitchAgent:
    heatswitchAgent: debug
    mkidcontrol.mkidredis: debug
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  lakeshore336Agent:
    lakeshore336Agent: debug
    mkidcontrol.mkidredis: info
    mkidcontrol.devices: debug
    serial: debug
    "":
      handlers: [ default ]
      level: INFO
      propagate: False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  lakeshore372Agent:
    lakeshore372Agent: debug
    mkidcontrol.mkidredis: info
    mkidcontrol.devices: debug
    serial: debug
    "":
      handlers: [ default ]
      level: INFO
      propagate: False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  lakeshore625Agent:
    lakeshore625Agent: debug
    mkidcontrol.mkidredis: debug
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  relayAgent:
    relayAgent: debug
    mkidcontrol.mkidredis: info
  quenchAgent:
      quenchAgent: debug
      mkidcontrol.mkidredis: info
  sim921Agent:
    sim921Agent: debug
    mkidcontrol.mkidredis: info
    mkidcontrol.devices: debug
    serial: debug
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False
  sim960Agent:
    sim960Agent: debug
    mkidcontrol.devices: debug
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate: False

version: 1
disable_existing_loggers: False
handlers:
  default:
    class : logging.StreamHandler
    formatter: default
    level   : DEBUG
    stream  : ext://sys.stdout
formatters:
  brieffmt:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(name)s:%(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
