loggers:
  piccDirector:
    werkzeug: warning
    piccDirector:
      handlers: [ default ]
      level: DEBUG
      propagate: False
    "":
      handlers: [ default ]
      level: WARNING
      propagate': False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate': False
  lakeshore240Agent: info
  currentduinoAgent:
    currentduinoAgent: debug
    picturec.pcredis: info
  hemttempAgent:
    hemttempAgent: debug
    picturec.pcredis: info
  quenchAgent:
      quenchAgent: debug
      picturec.pcredis: info
  sim921Agent:
    sim921Agent: debug
    picturec.pcredis: info
    picturec.devices: debug
    serial: debug
    "":
      handlers: [ default ]
      level: WARNING
      propagate': False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate': False
  sim960Agent:
    sim960Agent: debug
    picturec.devices: debug
    "":
      handlers: [ default ]
      level: WARNING
      propagate': False
    __main__:
      handlers: [ default ]
      level: DEBUG
      propagate': False

version: 1
disable_existing_loggers: False
handlers:
  default:
    class : logging.StreamHandler
    formatter: default
    level   : DEBUG
    stream  : ext://sys.stdout
formatters:
  brieffmt:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(name)s:%(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
